Update documentation to provide details on using the developer portal
lenushealth/sandbox-docs pull request #12
Opened 2021-07-30 13:44 UTC by Philo

Also updates agency documentation to include reference to the `subject` querystring parameter returned using an agency request using the `clientNotifyPath`

2021-07-30 14:03 UTC, alexszym requested changes

2021-07-30 14:03 UTC, alexszym commented on developer-portal/index.md
> +When you initially create your client application it will be created a random client secret, you can update this value as do a secure value that you will need to store as it can not be provided back
Also 2 sentences.


value *to a* secure

2021-07-30 14:05 UTC, alexszym commented on developer-portal/index.md
> +The Lenus Health Developer Portal is designed for service developers creating and managing client applications used to authenticate and communicate with our platform.  As our platform's authenticatio
Sorry. Github doesn't allow to tag a specific place in a sentence. Meant  this:

service**,** developers

2021-07-30 14:12 UTC, Philo commented on agency/index.md
> +- The user will be redirected to the provided `browserRedirectPath`, the following querystring parameters will be included:
I'm tempted to say we would be better providing the detail in the openapi spec document rather than in here?  The spec doesn't have this level of detail at the moment so could be updated, what do you think?

2021-07-30 14:15 UTC, Philo commented on developer-portal/index.md
> +In order to access our developer portal you will need a Lenus account, you can register an account with your email address by visiting our sandbox environment.  Once you have created an account we wi
If I make it more vague by removing specific references to "developer tenancy" that will mean updating a few other sections through this page, is that what you mean?

2021-08-04 09:23 UTC, Philo commented on agency/index.md
> +- An asynchronous GET request will be made to the `clientNotifyPath`, the following querystring parameters will be included:
I have added sub-headings and examples of each

2021-08-04 09:29 UTC, Philo commented on agency/index.md
> +- The user will be redirected to the provided `browserRedirectPath`, the following querystring parameters will be included:
@alexszym - I have expanded the examples and also tweaked the content in the openapi spec documentation, do you think we need to go further with descrbing specifics in the documentation vs the openspi spec?

2021-08-04 09:36 UTC, alexszym commented on agency/index.md
> +- The user will be redirected to the provided `browserRedirectPath`, the following querystring parameters will be included:
Based on the feedback we had from one of the developers documentation is a better place for it rather than API spec.

2021-08-04 09:38 UTC, alexszym commented on developer-portal/index.md
> +In order to access our developer portal you will need a Lenus account, you can register an account with your email address by visiting our sandbox environment.  Once you have created an account we wi
"Once you have created an account you will need to get in touch with our support team to start the configuration process." - I meant something more like this

2021-08-05 12:21 UTC, alexszym commented on developer-portal/index.md
> +When you initially create your client application it will be created a random client secret.  You can update this value as do a secure value that you will need to store as it can not be provided back
```suggestion
When you initially create your client application it will be created with a random client secret.  You can update this value to a secure value that you will need to store as it can not be provided back to you once set.
```

2021-08-05 12:21 UTC, alexszym commented on index.md
> +Firstly you will need to on-boarded to our [developer portal](../developer-portal), after which you are free to create client applications and interface with the Lenus Health platform.
```suggestion
Firstly you will need to be on-boarded to our [developer portal](../developer-portal), after which you are free to create client applications and interface with the Lenus Health platform.
```

2021-08-05 12:24 UTC, alexszym commented on developer-portal/index.md
> +In order to access our developer portal you will need a Lenus account, you can register an account with your email address by visiting our sandbox environment.  Once you have created an account we wi
looks good.

2021-08-05 14:32 UTC, Philo commented on agency/agency.v1.openapi.yaml
>                    description: An organization id for a known organisation, if provided the agency request will be issued on behalf of the organisation, acceptance of this by the user will result in
Yea, you are right, I just hate the fact we coded American English into this API 😠

2021-08-12 12:28 UTC, merged